- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 2.5h
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  guides: # goobstation
  - MedicalDoctor
  - Medical
  - Medicine
  goobcoins: 20 #Goob content
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: DoctorDay
    prototype: WehMedipen
  - !type:AddComponentSpecial # Trauma
    components:
    - type: SurgerySpeedModifier
      speedModifier: 1.5
    - type: CPRTraining
      reviveChance: 0.45 # a bit better at chest compressions
      inhaleChance: 0.75 # decent at mouth to mouth res.

- type: startingGear
  id: DoctorGear
  equipment:
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: MedicalDoctorChameleonOutfit
  job: MedicalDoctor
  equipment:
    head: ClothingHeadNurseHat
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
