- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  requirements:
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 2.5h
  startingGear: ParamedicGear
  icon: "JobIconParamedic"
  supervisors: job-supervisors-cmo
  guides: # goobstation
  - MedicalDoctor
  - Medical
  - Medicine
  goobcoins: 20 #Goob content
  access:
  - Medical
  - Maintenance
  - External # goobstation
  extendedAccess:
  - Chemistry
  special: # Trauma
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining
      reviveChance: 0.6 # better at chest compressions
      inhaleChance: 0.9 # very good at mouth to mouth res.

- type: startingGear
  id: ParamedicGear
  equipment:
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalEMTFilled
  storage:
    back:
    - EmergencyRollerBedSpawnFolded

- type: chameleonOutfit
  id: ParamedicChameleonOutfit
  job: Paramedic
  equipment:
    head: ClothingHeadHatParamedicsoft
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatParamedicWB
    gloves: ClothingHandsGlovesLatex
